stages:
  - test
  - report

ui-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.43.0-focal
  script:
    - npm ci
    - npm install -g allure-commandline --no-progress
    - npx playwright install --with-deps
    - npx playwright test --project=ui-regression || true
    - allure generate --clean allure-results -o allure-report
  artifacts:
    paths:
      - allure-results
      - allure-report
    when: always